### ISSUE TITLE
Fail to add Microsoft.ServiceFabric.Actors

### ISSUE THREAD

**Issue by Shrn-Prmshr** [Azure-Samples/service-fabric-dotnet-core-getting-started#4]
I have my SF/ActorModel project in .NetFramework and now I need to migrate that to .NetCore. 
I did not manage to add _Microsoft.ServiceFabric.Actors_ package to my project.

> Package Microsoft.ServiceFabric 5.6.220 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.ServiceFabric 5.6.220 supports: net45 (.NETFramework,Version=v4.5) Package Microsoft.ServiceFabric.Data 2.6.220 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.ServiceFabric.Data 2.6.220 supports: net45 (.NETFramework,Version=v4.5) Package Microsoft.ServiceFabric.Services 2.6.220 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.ServiceFabric.Services 2.6.220 supports: net45 (.NETFramework,Version=v4.5) Package Microsoft.ServiceFabric.Services.Remoting 2.6.220 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.ServiceFabric.Services.Remoting 2.6.220 supports: net45 (.NETFramework,Version=v4.5) Package Microsoft.ServiceFabric.FabricTransport.Internal 2.6.220 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.ServiceFabric.FabricTransport.Internal 2.6.220 supports: net45 (.NETFramework,Version=v4.5) One or more packages are incompatible with .NETCoreApp,Version=v1.0. Package restore failed. Rolling back package changes for '...'.

Am I missing anything?

**Comment by karolz-ms** [comment]
Support for .NET Core CLR for Service Fabric services is coming, but as of today, Service Fabric requires full framework, it won't work on top of Core CLR. You can use .NET Core _packages_, but your service must be running on full framework.

**Comment by Aleksanderis** [comment]
I don't get it.. why this "getting started" example posted then? It targets netcoreapp1.0 (VisualObjects.Common also targets netstandard1.6), but it fails to compile, because it needs "full" framework as you say.
I didn't try to compile it with `build.sh` as suggested in readme, but not sure if it's the case if it cannot be compiled from Visual Studio.

So what's the gotcha here with this example? Does it really work?
